### ISSUE TITLE
Let's convert the script from CoffeeScript to JavaScript

### ISSUE THREAD

**Issue by KeesCBakker** [hubot-archive/hubot-pager-me#216]
Hi, I would love to contribute to the script, but coffee is something I drink, not code. Can we convert the code to JavaScript?

**Comment by stephenyeargin** [comment]
I think that would be a good move, particularly with the [plan to drop CoffeeScript support](https://github.com/hubotio/hubot/issues/1658). This one, like `hubot-grafana` is a fairly important one for incident response, so lets tread carefully. It also has a pattern where parts of it are abstracted away from the responders, so it may be easier to test in isolation compared to it all being in a single file.

**Comment by KeesCBakker** [comment]
This this project might benefit from some API mock testing as well, but they are currently not in place.

**Comment by KeesCBakker** [comment]
Any plans on releasing?

**Comment by joeyguerra** [comment]
@stephenyeargin Hubot uses semantic-release for it's releases: https://github.com/hubotio/hubot/blob/4ec126bec9ca3eb590d3b5ad99a35fcbd0957a6c/.github/workflows/pipeline.yml#L82

**Comment by stephenyeargin** [comment]
Fixed by #217
